# Analysis

_Importing Libraries:_

In [1]:
import pandas as pd

*_Reading in the data:_*

Let's read in the cleaned data and take a look at the first 10 rows to get an idea of what it looks like inside.

In [2]:
# using pd.read_csv() to read in the cleaned data set, then showing the first 10 rows using .head() to get an idea of what's inside
df = pd.read_csv("market_data_cleaned.csv")

df.head(10)

,Date,SP500_Close,SP500_High,SP500_Low,SP500_Open,SP500_Volume,Nasdaq_Close,Nasdaq_High,Nasdaq_Low,Nasdaq_Open,...,DowJones_High,DowJones_Low,DowJones_Open,DowJones_Volume,10Y_Treasury_Yield,Gold_Close,Gold_High,Gold_Low,Gold_Open,Gold_Volume
0,2010-01-12,1136.219971,1143.810059,1131.770020,1143.810059,4.716160e+09,2282.310059,2298.850098,2272.699951,2297.280029,...,10663.080078,10568.839844,10662.860352,256050000.0,3.74,1128.900024,1157.199951,1127.199951,1128.900024,51.0
1,2010-01-13,1145.680054,1148.400024,1133.180054,1137.310059,4.170360e+09,2307.899902,2313.030029,2274.120117,2289.459961,...,10709.259766,10614.490234,10628.089844,202810000.0,3.80,1136.400024,1136.400024,1121.000000,1136.400024,58.0
2,2010-01-14,1148.459961,1150.410034,1143.800049,1145.680054,3.915200e+09,2316.739990,2322.560059,2303.290039,2303.310059,...,10723.769531,10666.860352,10680.160156,201320000.0,3.76,1142.599976,1145.900024,1132.800049,1137.000000,81.0
3,2010-01-15,1136.030029,1147.770020,1131.390015,1147.719971,4.758730e+09,2287.989990,2322.540039,2279.199951,2316.979980,...,10709.940430,10561.059570,10706.990234,362930000.0,3.70,1130.099976,1133.400024,1127.199951,1132.800049,50.0
4,2010-01-19,1150.229980,1150.449951,1135.770020,1136.030029,4.724830e+09,2320.399902,2320.399902,2290.679932,2291.020020,...,10729.889648,10591.969727,10608.370117,192150000.0,3.73,1139.699951,1139.699951,1130.500000,1139.699951,22.0
5,2010-01-20,1138.040039,1147.949951,1129.250000,1147.949951,4.810560e+09,2291.250000,2304.469971,2268.679932,2304.310059,...,10719.919922,10517.299805,10719.690430,203270000.0,3.68,1112.300049,1133.000000,1109.800049,1123.300049,28.0
6,2010-01-21,1116.479980,1141.579956,1114.839966,1138.680054,6.874290e+09,2265.699951,2308.979980,2259.820068,2298.229980,...,10614.940430,10374.690430,10603.910156,304290000.0,3.62,1102.699951,1107.500000,1090.199951,1102.699951,99.0
7,2010-01-22,1091.760010,1115.489990,1090.180054,1115.489990,6.208650e+09,2205.290039,2262.270020,2200.370117,2255.760010,...,10389.580078,10157.639648,10389.580078,323620000.0,3.62,1089.199951,1095.400024,1083.000000,1089.199951,58.0
8,2010-01-25,1096.780029,1102.969971,1092.400024,1092.400024,4.481390e+09,2210.800049,2223.219971,2201.169922,2220.290039,...,10256.870117,10171.769531,10175.099609,215330000.0,3.66,1095.199951,1095.199951,1095.199951,1095.199951,8.0
9,2010-01-26,1092.170044,1103.689941,1089.859985,1095.800049,4.731910e+09,2203.729980,2227.889893,2195.439941,2203.439941,...,10285.129883,10155.599609,10195.349609,217300000.0,3.65,1097.900024,1097.900024,1097.900024,1097.900024,4.0